apiVersion: apps/v1                                                                       
kind: Deployment
metadata:    
  creationTimestamp: null
  labels:    
    app: app-1
  name: app-1
  namespace: test
spec:        
  selector:  
    matchLabels:
      app: app-1
  strategy: {}
  template:  
    metadata:
      creationTimestamp: null
      labels:
        app: app-1
    spec:    
      containers:
      - image: redis:5.0.4
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
